### ISSUE TITLE
index out of bound panic when provided old max version is not installed

### ISSUE THREAD

**Issue by edward-shen** [foresterre/cargo-msrv#369]
Repro steps (Need confirmation):

1. Check the list of installed toolchains with `rustup show`:
```
-snip-

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
1.46.0-x86_64-unknown-linux-gnu
1.55.0-x86_64-unknown-linux-gnu
1.56.1-x86_64-unknown-linux-gnu
1.57.0-x86_64-unknown-linux-gnu
1.58.1-x86_64-unknown-linux-gnu
1.59.0-x86_64-unknown-linux-gnu

-snip-

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```
2. Ensure the max version you want to install is older than 3 minor version and is not installed. I've tested this with `1.54.0`.
3. Run `cargo msrv --max 1.54.0`

`cargo-msrv` version: 0.15.1

[Full backtrace with trace log level](https://pastebin.com/VyKjt14Z)

Notes:
 - Looks like this is caused by a `Bisector::try_bisect` call in [`bisect.rs`](https://github.com/foresterre/cargo-msrv/blob/main/src/search_methods/bisect.rs#L74)
 - [`Bisector::try_bisect`](https://github.com/foresterre/bisector/blob/main/src/lib.rs#L121) seems to panic at the [array-index operation](https://github.com/foresterre/bisector/blob/main/src/lib.rs#L136) with `9223372036854775807`, which appears to be which suggest `index.middle()` is returning a negative value and being re-interpreted as an unsigned value.
 - [`Indices::middle`](https://github.com/foresterre/bisector/blob/main/src/lib.rs#L206) is defined as `(self.left + self.right) / 2`, and [`Indices::from_bisector`](https://github.com/foresterre/bisector/blob/main/src/lib.rs#L196) sets itself to 0 and the length of the bisector's view - 1.
 - If the bisector's length is 0, this leads to an underflow where the right value of a Indices is set to -1, which is 18446744073709551615 when interpreted as a u64 (usize).
 - Then, as a result, `Indices::middle` calculates half of that, which is exactly `9223372036854775807`.

Not sure what the best solution is, but I think the cleanest one should be to make `Indices::from_bisector` fallible, e.g. rename it to `Indices::try_from_bisector` and set the output type to `Result<Self, E>`.

**Comment by foresterre** [comment]
Welp, thanks for the detailed report!

**Comment by foresterre** [comment]
Could it be that the project you're running cargo-msrv in, uses edition 2021 (i.e. in Cargo.toml, is the `package.edition` value "2021")?

I think that an important observation which we can make here is that the `max` rust version is smaller than the `min` rust version, and as such, the set of releases is empty. Even though the `min` version is not specified by hand, if an edition is specified, we take the version corresponding to the first version supporting said edition on stable as the `min` rust version.

If we take your list of installed toolchains with `rustup show` as example, and assume the edition is set to [2021](https://doc.rust-lang.org/edition-guide/rust-2021/index.html), then:
* `min` version is `1.56` <sub>by virtue of being the first version which supports edition 2021 (this is implicit)</sub>
* `max` version is `1.54.0` <sub>as per `--max 1.54.0`</sub>

My hypothesis is that the following happens:
* Since `max < min`, the set of toolchains to be checked is empty
* When we [create](https://github.com/foresterre/cargo-msrv/blob/d3671162edaf41f179573816ae71805a02cfbd2f/src/search_methods/bisect.rs?rgh-link-date=2022-05-25T06%3A09%3A41Z#L62) our `Bisector` via [Bisector::new](https://github.com/foresterre/bisector/blob/5681c18fd0cc3aa0e7883b2de716bdf292bc8c16/src/lib.rs#L39-L41), it will be composed of just an empty slice `&[]`.
* When create the initial indices via [Indices::from_bisector](https://github.com/foresterre/cargo-msrv/blob/d3671162edaf41f179573816ae71805a02cfbd2f/src/search_methods/bisect.rs?rgh-link-date=2022-05-25T06%3A09%3A41Z#L65), the [right](https://github.com/foresterre/bisector/blob/5681c18fd0cc3aa0e7883b2de716bdf292bc8c16/src/lib.rs#L199) index will underflow
  * Importantly though: this only happens when rustc is in release mode
  * In rustc debug mode, [`Indices::from_bisector`](https://github.com/foresterre/bisector/blob/5681c18fd0cc3aa0e7883b2de716bdf292bc8c16/src/lib.rs#L193-L199) will panic on a bounds check instead, as asserted by its docs.

**Comment by edward-shen** [comment]
> Could it be that the project you're running cargo-msrv in, uses edition 2021 (i.e. in Cargo.toml, is the package.edition value "2021")?

Sadly I can't verify this, but it sounds very plausible. I was using `cargo-msrv` to see if I could get [a crate](https://github.com/edward-shen/actix-csrf) down to 1.54.0 (to match the MSRV of the framework crate) and it was previously on the 2021 edition, tested only with the latest version. I think at some point I did in fact need to change it, and it was after letting `cargo-msrv` tell me that I needed to use the older edition after setting `--min 1.54.0`.
